#!/usr/bin/env python3
import argparse
import ipaddress
import pathlib
import shelve
import sys
from collections import defaultdict
import datetime
import datetime

def group_ips_into_cidrs(ip_list: list) -> list:
    """
    Takes a flat list of IP address strings and groups them into
    /24 CIDR blocks where possible.
    """
    # Group individual IPs under their /24 network
    cidrs = defaultdict(list)
    for ip_str in ip_list:
        try:
            ip_obj = ipaddress.ip_address(ip_str)
            if ip_obj.version == 4:
                network = ipaddress.ip_network(f"{ip_str}/24", strict=False)
                cidrs[str(network)].append(ip_str)
            else:
                # Don't try to group IPv6 for now, just pass them through
                cidrs[ip_str].append(ip_str)
        except ValueError:
            continue # Skip invalid IPs

    # Consolidate and build the final list
    final_list = []
    for cidr, ips in cidrs.items():
        # If a CIDR group has more than 5 IPs, or more than 5% of the /24,
        # just use the CIDR block. Otherwise, keep the individual IPs.
        if len(ips) > 5 or len(ips) > (254 * 0.05):
            final_list.append(cidr)
        else:
            final_list.extend(ips)
    
    return sorted(final_list)

def write_ban_list_file(filename: str, header: str, ban_list: list):
    """Writes the ban list and its metadata header to a file."""
    try:
        with open(filename, 'w') as f:
            f.write(header)
            f.write("\n".join(ban_list))
        print(f"Successfully wrote ban list to {filename}")
    except Exception as e:
        print(f"Error writing to output file {filename}: {e}", file=sys.stderr)

def main(cache_file_path: str, threshold: float, junk_output_file: str, restricted_output_file: str):
    """
    Generates ban lists from the analytics cache.
    """
    cache_file = pathlib.Path(cache_file_path)
    if not cache_file.exists():
        print(f"Error: Cache file '{cache_file}' not found. Please run generate_analytics.py first.", file=sys.stderr)
        sys.exit(1)
    
    print(f"Reading analytics from: {cache_file}")
    try:
        with shelve.open(str(cache_file), 'r') as cache:
            not_yet_banned_flat = cache.get('not_yet_banned', {})
            access_only_flat = cache.get('access_only', {})
    except Exception as e:
        print(f"Error opening or reading cache file: {e}", file=sys.stderr)
        sys.exit(1)
    
    # --- 1. Generate Ban List for Junk Probers ---
    if not_yet_banned_flat:
        print("\nProcessing 'not_yet_banned' IPs for junk prober ban list...")
        junk_prober_ips = list(not_yet_banned_flat.keys())
        total_requests = sum(v.get('total_request_count', 0) for v in not_yet_banned_flat.values())
        
        compressed_list = group_ips_into_cidrs(junk_prober_ips)
        
        header = (
            f"# Ban list for junk-probe IPs.\n"
            f"# Generated by: {pathlib.Path(__file__).name} at {datetime.datetime.now().isoformat()}\n"
            f"# Total unique IPs: {len(junk_prober_ips):,}\n"
            f"# Total associated requests: {total_requests:,}\n"
            f"# Compressed to {len(compressed_list):,} entries.\n#\n"
        )
        write_ban_list_file(junk_output_file, header, compressed_list)
    else:
        print("\nNo 'not_yet_banned' data found, skipping junk prober ban list.")

    # --- 2. Generate Ban List for Restricted Path Violators ---
    if access_only_flat:
        print(f"\nProcessing 'access_only' IPs for restricted path violators (Threshold > {threshold:.0%})...")
        
        violator_ips = []
        total_requests = 0
        for ip, data in access_only_flat.items():
            reqs = data.get('total_request_count', 0)
            restricted = data.get('restricted_path_count', 0)
            if reqs > 0 and (restricted / reqs) > threshold:
                violator_ips.append(ip)
                total_requests += reqs
        
        compressed_list = group_ips_into_cidrs(violator_ips)

        header = (
            f"# Ban list for restricted-path violators (>{threshold:.0%} violation ratio).\n"
            f"# Generated by: {pathlib.Path(__file__).name} at {datetime.datetime.now().isoformat()}\n"
            f"# Total unique IPs found: {len(violator_ips):,}\n"
            f"# Total associated requests: {total_requests:,}\n"
            f"# Compressed to {len(compressed_list):,} entries.\n#\n"
        )
        write_ban_list_file(restricted_output_file, header, compressed_list)
    else:
        print("\nNo 'access_only' data found, skipping restricted path violator ban list.")




if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate ban lists from the analytics cache."
    )
    parser.add_argument(
        '--cache-file',
        default='static/cache/analytics.db',
        help="Path to the shelve cache file to read."
    )
    parser.add_argument(
        '--threshold',
        type=float,
        default=0.8,
        help="Violation ratio threshold for banning IPs from 'access_only' data (default: 0.8)."
    )
    parser.add_argument(
        '--output-junk-file',
        default='junk_probers_banlist.txt',
        help="Output file for the junk probers ban list."
    )
    parser.add_argument(
        '--output-restricted-file',
        default='restricted_violators_banlist.txt',
        help="Output file for the restricted path violators ban list."
    )
    args = parser.parse_args()
    main(args.cache_file, args.threshold, args.output_junk_file, args.output_restricted_file)
